[package]
name = 'donervan'
version = '0.1.0'
edition = '2021'

[dependencies]
indexmap = '1.9.1'
strum = { version = '0.24.1', features = ['derive'] }
strum_macros = '0.24.1'

[dev-dependencies]
paste = '1.0.7'
